### ISSUE TITLE
PETSC with OpenFOAM

### ISSUE THREAD

**Issue by skakarla1982** [barbagroup/AmgXWrapper#28]
Hi ,

I want to use PETSC with OpenFOAM.
I have couple of questions .
Q1 . OpenFOAM matrix support LDU and PETSC supports CSR format
Q2 .Is there any example code or reference can you provide for PETSC with OPenFOAM   ? 

Thank you,
Srinivas

**Comment by piyueh** [comment]
Hi, we have limited knowledge of OpenFOAM because we don't use it. However, I think there's an interface for using PETSc with OpenFOAM: https://develop.openfoam.com/modules/external-solver

**Comment by srinivas1982** [comment]
Hi ,

Than you for update.
